#!/bin/bash

CURRDIR=`pwd`
SCRIPTDIR=$(cd `dirname $0` && pwd)

# Update git submodules
cd $SCRIPTDIR
git pull
git submodule update --init
cd vim-config
git submodule update --init

# Create Links
cd ~
[[ ! -L .bashrc ]] && [[ -f .bashrc ]] && mv .bashrc .bashrc.old
[[ ! -L .bashrc ]] && ln -s $SCRIPTDIR/bashrc .bashrc
[[ ! -L .bashrc.`uname` ]] && ln -s $SCRIPTDIR/bashrc.`uname` .bashrc.`uname`
[[ ! -L .gitconfig ]] && ln -s $SCRIPTDIR/gitconfig .gitconfig
[[ ! -L .git-global-ignore ]] && ln -s $SCRIPTDIR/git-global-ignore .git-global-ignore
[[ ! -L .tigrc ]] && ln -s $SCRIPTDIR/tigrc .tigrc
[[ ! -L .vim ]] && ln -s $SCRIPTDIR/vim-config .vim
[[ ! -L .vimrc ]] && ln -s .vim/vimrc .vimrc
[[ ! -L .screenrc ]] && ln -s $SCRIPTDIR/screenrc .screenrc
[[ ! -L .zshrc ]] && ln -s $SCRIPTDIR/zshrc .zshrc
[[ ! -L .irssi ]] && ln -s $SCRIPTDIR/irssi .irssi
mkdir -p .config
cd .config
[[ ! -L nvim ]] && ln -s $SCRIPTDIR/nvim nvim
cd ~
mkdir -p bin
cd bin
[[ ! -L z.sh ]] && ln -s $SCRIPTDIR/z/z.sh
[[ ! -L e ]] && ln -s $SCRIPTDIR/bin/e

# run os-specific shit
$SCRIPTDIR/bootstrap.`uname`

# run company-specific shit
if [ "$1" = "netflix" ]; then
  cd ~
  [[ ! -d dotfiles-netflix ]] && git clone ssh://git@stash.corp.netflix.com:7999/~jigishp/dotfiles.git dotfiles-netflix
  cd dotfiles-netflix
  git pull
  ./bootstrap
fi

cd $CURRDIR
