- keyboards: [ "AT Translated Set 2 keyboard" ]
  keymap:
    capslock: esc
    leftalt: leftmeta
    leftmeta: leftalt
- keyboards: [ "KBDFANS KBD75_HOTSWAP", "KBDFANS KBD75_HOTSWAP Keyboard" ]
  keymap:
    capslock: esc
